<header role="banner">
    <div id='tag'><p>[ <a href='../php_includes/logout.php'>Sign Out</a> ]</div>
    <h1 class="headerlink"><a href="main.php">Shine Administrator</a></h1>
</header>
<nav role="navigation">
    <ul>
        <li><a href="main.php">Action</a></li>
        <li><a href="author.php">Authors</a></li>
        <li><a href="profiles.php">Profiles</a></li>
        <li><a href="templates.php">Planning Templates</a></li>
        <li><a href="database.php">Database</a></li>
    </ul>
</nav>