<header role="banner">
    <div id="tag">[ <a href="index.php">Sign Out</a> ]</div>
    <h1 class="headerlink" style="text-align: left"><a href="main.php">Shine</a></h1>
</header>

<nav role="navigation">
    <ul>
        <li><a href="profile_create.php">Create Profile</a></li>
        <li><a href="profile.php">View Profile</a></li>
        <li><a href="edit.php">Edit Profile</a></li>
        <li><a href="share.php">Share Profile</a></li>
        <li><a href="settings.php">Settings</a></li>
        <li><a href="upgrade.php">Upgrade</a></li>
    </ul>
</nav>